#!/bin/bash

#Used to define package dependencies

DEBIAN_DEPENDENCIES="python-pip python-setuptools python-dev python-m2crypto python-openssl python-flup nginx"
PIP_DEPENDENCIES="SQLAlchemy flask Flask-XML-RPC python-dateutil blinker pika"
EASY_INSTALL_DEPENDENCIES=""
