#!/bin/bash

###
#       @author: msune
#	@organization: i2CAT
#	@project: Ofelia FP7
#	@description: backup module
###

# error not allowed upgrade!
error "Not Allowed upgrade action! [for now :-)]"

#inforr user
printHeader "info#" "Using default backup module..."

#Do a backup of the Database and files
print "Doing a backup of the files and/or Database..."
print 'Saving contents using the built-in variable $BACKUP_PATH, with the value of:'"$BACKUP_PATH"
sleep 2

