#!/bin/bash

###
#   @author: roberto monno, msune
#	@organization: NXW, i2CAT
#	@project: FIBRE FP7, Ofelia FP7
#	@description: install module 
###

#Inform user
printHeader "info#" "Using install module..."

##Main routing

#Install dependencies
printHeader ">" "Installing dependencies through apt-get..."

#Loading dependencies. Note that loadModule will load specific version dependencies file if exists
loadModule lib/dependencies $NO_RESCUE

local APTGET=`which apt-get`
$APTGET clean
$APTGET autoclean
$APTGET update
$APTGET -y install $DEBIAN_DEPENDENCIES || error "Could not install dependencies (apt-get)" $NO_RESCUE

printHeader ">" "Installing dependencies through pip..."

local PIP=`which pip`
$PIP install $PIP_DEPENDENCIES || error "Could not install dependencies (pip)" $NO_RESCUE

#Calling procedure1 (don't call rollback in case of error)
loadModule lib/procedure1 $NO_RESCUE

#Calling procedure2
loadModule lib/procedure2 $NO_RESCUE


