#!/bin/bash

###
#       @author: msune
#	@organization: i2CAT
#	@project: Ofelia FP7
#	@description: post-install module
###

#Inform user
printHeader "info#" "Using default post-install-hook module..."

#Starting apache
print "Starting application..."

sleep 2

print "Here you could clean the house..."
