#!/bin/bash

###
#   @author: roberto monno, msune
#	@organization: NXW, i2CAT
#	@project: FIBRE FP7, Ofelia FP7
#	@description: post-install module
###

#Inform user
printHeader "info#" "Using post-install-hook module..."

#Starting roadm-am
print "Starting Roadm-AM application..."
local DEST_DIR=${DESTINATION_DIR:-'../src'}
local PYTHON=`which python`
$PYTHON $DEST_DIR/src/main.py || error "Unable to start the main plugin!"

sleep 2

print "Here you could clean the house..."
