#!/bin/bash

###
#   @author: roberto monno, msune
#	@organization: NXW, i2CAT
#	@project: FIBRE FP7, Ofelia FP7
#	@description: post-install module
###

#Inform user
printHeader "info#" "Using post-install-hook module..."

#Starting roadm-am
print "Starting Roadm-AM application (as a daemon)..."

local SERVICE=`which service`
$SERVICE RoadmAMService start

local SLEEP_T=${SLEEP_TIME:-5}
local SLEEP=`which sleep`

print "Starting Roadm-AM Worker application (as a daemon)..."
$SERVICE RoadmAMServiceWorker start
