#!/bin/bash

###
#       @author: msune
#	@organization: i2CAT
#	@project: Ofelia FP7
#	@description: pre-install module 
###

#inform user
printHeader "info#" "Using default pre-install-hook module..."

#shutdown apache
print "Stopping application (for instance apache(emulating))..."

sleep 2

print "Application stopped!"

