#!/bin/bash

#!/bin/bash

###
#       @author: msune
#	@organization: i2CAT
#	@project: Ofelia FP7
#	@description: application repository download code. Note that this is only used if OFVER_IN_BRANCH == 0 
###

#/usr/bin/git clone http://somewhere.com/git
error "Change-me. Modify this file to include clone&install commands (git clone, svn co...) for downloading APPLICATION code."
